# If you would like to change the commands to something else, this can be done in the commands.yml file.
# View this page for help on adding command aliases: http://wiki.bukkit.org/Commands.yml
name: ExpBank
description: This plugin allows players to store XP into a bank represented by a sign.
main: com.empcraft.xpbank.ExpBank
version: 2
author: Empire92, bmhm
website: www.empcraft.com
depend:
  - ProtocolLib
